/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/Timeline'
import { Route as NewsletterRouteImport } from './routes/Newsletter'
import { Route as DonateRouteImport } from './routes/Donate'
import { Route as ContactRouteImport } from './routes/Contact'
import { Route as ApproachRouteImport } from './routes/Approach'
import { Route as IndexRouteImport } from './routes/index'

const TimelineRoute = TimelineRouteImport.update({
  id: '/Timeline',
  path: '/Timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/Newsletter',
  path: '/Newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/Donate',
  path: '/Donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/Contact',
  path: '/Contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/Approach',
  path: '/Approach',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Approach': typeof ApproachRoute
  '/Contact': typeof ContactRoute
  '/Donate': typeof DonateRoute
  '/Newsletter': typeof NewsletterRoute
  '/Timeline': typeof TimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Approach': typeof ApproachRoute
  '/Contact': typeof ContactRoute
  '/Donate': typeof DonateRoute
  '/Newsletter': typeof NewsletterRoute
  '/Timeline': typeof TimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Approach': typeof ApproachRoute
  '/Contact': typeof ContactRoute
  '/Donate': typeof DonateRoute
  '/Newsletter': typeof NewsletterRoute
  '/Timeline': typeof TimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Approach'
    | '/Contact'
    | '/Donate'
    | '/Newsletter'
    | '/Timeline'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Approach' | '/Contact' | '/Donate' | '/Newsletter' | '/Timeline'
  id:
    | '__root__'
    | '/'
    | '/Approach'
    | '/Contact'
    | '/Donate'
    | '/Newsletter'
    | '/Timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApproachRoute: typeof ApproachRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  NewsletterRoute: typeof NewsletterRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Timeline': {
      id: '/Timeline'
      path: '/Timeline'
      fullPath: '/Timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Newsletter': {
      id: '/Newsletter'
      path: '/Newsletter'
      fullPath: '/Newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Donate': {
      id: '/Donate'
      path: '/Donate'
      fullPath: '/Donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Contact': {
      id: '/Contact'
      path: '/Contact'
      fullPath: '/Contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Approach': {
      id: '/Approach'
      path: '/Approach'
      fullPath: '/Approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApproachRoute: ApproachRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  NewsletterRoute: NewsletterRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
